2022-06-07 15:10:32,081 ERROR: Exception on /reset_password_request [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 171, in reset_password_request
    return render_template('reset_password_request.html',
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/denis/Dev/checkiner/app/templates/reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 21, in block 'content'
    {% block app_content %} {% endblock %}
  File "/home/denis/Dev/checkiner/app/templates/reset_password_request.html", line 7, in block 'app_content'
    {{ wtf.quick_form(form) }}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2022-06-07 15:11:17,938 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MiwiZXhwIjoxNjU0NjA0NDUyLjQ5NjYzNn0.pLfLijJgeyO2Gt4nnzXu0xaq03FYqGT-qaR1Js3j2kg [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 188, in reset_password
    return render_template('reset_password.html', form=form)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/denis/Dev/checkiner/app/templates/reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 21, in block 'content'
    {% block app_content %} {% endblock %}
  File "/home/denis/Dev/checkiner/app/templates/reset_password.html", line 7, in block 'app_content'
    {{ wtf.quick_form(form) }}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2022-06-07 15:11:34,920 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MiwiZXhwIjoxNjU0NjA0NDUyLjQ5NjYzNn0.pLfLijJgeyO2Gt4nnzXu0xaq03FYqGT-qaR1Js3j2kg [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 188, in reset_password
    return render_template('reset_password.html', form=form)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/denis/Dev/checkiner/app/templates/reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 21, in block 'content'
    {% block app_content %} {% endblock %}
  File "/home/denis/Dev/checkiner/app/templates/reset_password.html", line 7, in block 'app_content'
    <div class="col-md-4">
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
